name: Load testing workflow
on: [fork]

jobs:
  test:
    name: Run load test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 local test
        uses: grafana/run-k6-action@v1
        with:
          path: test.js
